# Kenya Administrative Hierarchy: County → Sub-County → Wards
# Source: Kenya National Assembly constituencies and wards data (IEBC)

KENYA_LOCATIONS = {
    "Mombasa": {
        "Changamwe": ["Port Reitz", "Kipevu", "Airport", "Changamwe", "Chaani"],
        "Jomvu": ["Jomvu Kuu", "Miritini", "Mikindani"],
        "Kisauni": ["Mjambere", "Junda", "Bamburi", "Mwakirunge", "Mtopanga", "Magogoni", "Shanzu"],
        "Nyali": ["Frere Town", "Ziwa La Ng'ombe", "Mkomani", "Kongowea", "Kadzandani"],
        "Likoni": ["Mtongwe", "Shika Adabu", "Bofu", "Likoni", "Timbwani"],
        "Mvita": ["Mji Wa Kale/Makadara", "Tudor", "Tononoka", "Shimanzi/Ganjoni", "Majengo"],
    },
    "Kwale": {
        "Msambweni": ["Gombato Bongwe", "Ukunda", "Kinondo", "Ramisi"],
        "Lungalunga": ["Pongwe/Kikoneni", "Dzombo", "Mwereni", "Vanga"],
        "Matuga": ["Tsimba Golini", "Waa", "Tiwi", "Kubo South", "Mackinon Road"],
        "Kinango": ["Ndavaya", "Puma", "Kinango", "Mackinnon Road", "Chengoni/Samburu", "Mwavumbo", "Kasemeni"],
    },
    "Kilifi": {
        "Kilifi North": ["Tezo", "Sokoni", "Kibarani", "Dabaso", "Matsangoni", "Watamu", "Mnarani"],
        "Kilifi South": ["Junju", "Mwarakaya", "Shimo La Tewa", "Chasimba", "Mtepeni"],
        "Kaloleni": ["Mariakani", "Kayafungo", "Kaloleni", "Mwanamwinga"],
        "Rabai": ["Rabai/Kisurutini", "Ruruma", "Kambe/Ribe"],
        "Ganze": ["Ganze", "Bamba", "Jaribuni", "Sokoke"],
        "Malindi": ["Jilore", "Kakuyuni", "Ganda", "Malindi Town", "Shella"],
        "Magarini": ["Marafa", "Magarini", "Gongoni", "Adu", "Garashi", "Sabaki"],
    },
    "Tana River": {
        "Garsen": ["Kipini East", "Garsen South", "Kipini West", "Garsen Central", "Garsen North", "Garsen West"],
        "Galole": ["Wayu", "Sala", "Hirimani", "Bangale", "Madogo", "Tana North"],
        "Bura": ["Chewele", "Tana River", "Nanighi", "Bura"],
    },
    "Lamu": {
        "Lamu East": ["Faza", "Kiunga", "Basuba"],
        "Lamu West": ["Shela", "Mkomani", "Hindi", "Mkunumbi", "Hongwe", "Witu", "Bahari"],
    },
    "Taita-Taveta": {
        "Taveta": ["Chala", "Mahoo", "Bombo Rangi/Ngolia", "Taveta"],
        "Wundanyi": ["Wundanyi/Mbale", "Werugha", "Wumingu/Kishushe", "Mwanda/Mgange"],
        "Mwatate": ["Rong'e", "Mwatate", "Bura/Maji Moto/Mkongani", "Chawia", "Wusi/Kishamba"],
        "Voi": ["Marungu", "Kaloleni", "Mbololo", "Sagala", "Ngolia", "Voi"],
    },
    "Garissa": {
        "Garissa Township": ["Iftin", "Waberi", "Galbet", "Township", "Waberi"],
        "Balambala": ["Balambala", "Dujis", "Mwandha"],
        "Lagdera": ["Modogashe", "Benane", "Goreale", "Maalimin", "Sabena", "Baraki"],
        "Dadaab": ["Damajale", "Liboi", "Dertu", "Dadaab", "Lagoole", "Abakaile", "Ifo"],
        "Fafi": ["Jarajila", "Fafi", "Nanighi", "Dekaharia", "Sagalem", "Bura"],
        "Ijara": ["Hulugho", "Ijara", "Masalani", "Sangailu", "Garsen North"],
    },
    "Wajir": {
        "Wajir North": ["Gurar", "Bute", "Korondile", "Malkagufu", "Lagboghol North", "Diif"],
        "Wajir East": ["Wagberi", "Township", "Khorof/Harar", "Lagboghol South"],
        "Tarbaj": ["Tarbaj", "Wargadud", "Sarman", "Kutulo"],
        "Wajir West": ["Arbajahan", "Kombole", "Uraai", "Hadado/Athibohol"],
        "Eldas": ["Eldas", "Della", "Lakoley South/Basir", "Elnur/Fino"],
        "Wajir South": ["Griftu", "Habaswein", "Lagbogol North", "Muddo Erbi", "Batalu"],
    },
    "Mandera": {
        "Mandera East": ["Neboi", "Warankara", "Lagsure", "Didiso", "Neboi"],
        "Banissa": ["Banissa", "Derkhale", "Gari", "Malkamari"],
        "Mandera North": ["Arabia", "Guticha", "Morothile", "Ashabito"],
        "Mandera South": ["Wargadud", "Shimbir Fatuma", "Khalalio", "Neboi"],
        "Mandera West": ["Libehia", "Lafey North", "Sala", "Township"],
        "Lafey": ["Lafey", "Fino", "Qumbis", "Lafey North"],
    },
    "Marsabit": {
        "Moyale": ["Moyale Township", "Butiye", "Sololo", "Golbo"],
        "North Horr": ["Dukana", "Maikona", "Turbi", "North Horr", "Illeret"],
        "Saku": ["Karare", "Marsabit Central", "Sagante/Jaldesa", "Arero", "Bubisa"],
        "Laisamis": ["Korr/Ngurunit", "Logologo", "Laisamis", "Loiyangalani"],
    },
    "Isiolo": {
        "Isiolo North": ["Wabera", "Bulla Pesa", "Chari", "Cherab", "Ngare Mara", "Oldonyiro", "Bulapesa"],
        "Isiolo South": ["Garbatulla", "Kinna", "Sericho"],
    },
    "Meru": {
        "Igembe South": ["Maua", "Kiegoi/Antuambui", "Athiru Gaiti", "Akachiu", "Kanuni"],
        "Igembe Central": ["Njia", "Township", "Kangeta", "Antubochio"],
        "Igembe North": ["Ntunene", "Antubetwe Kiongo", "Naathu", "Amwathi"],
        "Tigania West": ["Athiru Ruujine", "Atwereri", "Akithi", "Kianjai", "Nkomo"],
        "Tigania East": ["Mbeu", "Mitunguu", "Igandene", "Karama", "Muthara", "Mburiti"],
        "Central Imenti": ["Ntima East", "Ntima West", "Nkuene", "Igoji East", "Igoji West"],
        "Buuri": ["Timau", "Kisima", "Kiirua/Naari", "Ruiri/Rwarera", "Muthalari"],
        "North Imenti": ["Municipality", "Ntima East", "Ntima West", "Nkuene"],
        "South Imenti": ["Mitunguu", "Igoji East", "Igoji West", "Abothuguchi West", "Abothuguchi Central"],
    },
    "Tharaka-Nithi": {
        "Maara": ["Githongo", "Igambang'ombe", "South Imenti", "Abogeta East", "Abogeta West", "Mwimbi"],
        "Chuka/Igambang'ombe": ["Karingani", "Mugwe", "Igambang'ombe"],
        "Tharaka North": ["Gatunga", "Mukothima"],
        "Tharaka South": ["Nkondi", "Tharaka", "Chiakariga", "Marimba"],
    },
    "Embu": {
        "Manyatta": ["Ruguru", "Ngandori/Nginda", "Itabua", "Gaturi South", "Central"],
        "Runyenjes": ["Kagaari South", "Central Imenti", "Kagaari North", "Kyeni North", "Kyeni South"],
        "Mbeere South": ["Mwea", "Makima", "Mbeti North", "Mavuria", "Kiambere"],
        "Mbeere North": ["Siakago", "Evurore", "Gaturi North", "Kagaari North", "Kithimu"],
    },
    "Kitui": {
        "Mwingi North": ["Ngomeni", "Kyuso", "Mumoni", "Tseikuru"],
        "Mwingi West": ["Kyome/Thaana", "Nguutani", "Migwani", "Kiomo/Kyethani"],
        "Mwingi Central": ["Central", "Kivou", "Nguni", "Nuu", "mui"],
        "Kitui West": ["Mutonguni", "Kauwi", "Matinyani", "Kwa Mutonga/Kithumula"],
        "Kitui Rural": ["Kisasi", "Mwitika", "Kwavonza/Yatta", "Kanyangi"],
        "Kitui Central": ["Miambani", "Township", "Kyangwithya West", "Mulundi"],
        "Kitui East": ["Zombe/Mwitika", "Chuluni", "Nzambani", "Mutito/Kaliku"],
        "Kitui South": ["Ikanga/Kyatune", "Mutomo", "Mutha", "Ikutha", "Kanziku", "Athi"],
    },
    "Machakos": {
        "Masinga": ["Masinga Central", "Ekalakala", "Miwani", "Kivaa", "Kiome"],
        "Yatta": ["Ndalani", "Matuu", "Kithimani", "Ikombe", "Katangi"],
        "Kangundo": ["Kangundo North", "Kangundo Central", "Kangundo East", "Kangundo West"],
        "Matungulu": ["Tala", "Matungulu North", "Matungulu East", "Matungulu West", "Kithyoko"],
        "Kathiani": ["Mitaboni", "Kathiani Central", "Upper Kaewa/Iveti", "Lower Kaewa"],
        "Mavoko": ["Syokimau/Mulolongo", "Athi River", "Kinanie"],
        "Machakos Town": ["Mutituni", "Machakos Central", "Kalama", "Mua", "Muvuti/Kiindu"],
        "Mwala": ["Mbiuni", "Makaveti/Nziu", "Kibauni", "Visoi", "Mwala", "Syiia"],
    },
    "Makueni": {
        "Mbooni": ["Tulimani", "Mbooni", "Kithungo/Kitundu", "Ivingoni/Nzambani"],
        "Kilome": ["Kasikeu", "Mukaa", "Kiima Kimwe/Kalawa"],
        "Kaiti": ["Kaiti", "Muvau/Kikumini", "Wote", "Kalawa"],
        "Makueni": ["Nguu/Masumba", "Mbuvo", "Kathonzweni", "Nzaui/Kilili/Kalamba"],
        "Kibwezi West": ["Makindu", "Nguumo", "Kikumbulyu North", "Kikumbulyu South", "Nguu/Masumba"],
        "Kibwezi East": ["Emali/Mulala", "Kibwezi", "Masongaleni", "Mtito Andei", "Thange"],
    },
    "Nyandarua": {
        "Kinangop": ["Engineer", "Gathara", "North Kinangop", "Murungaru", "Njabini/Kiburu"],
        "Kipipiri": ["Geta", "Githioro", "Kipipiri", "Wanjohi"],
        "Ol Kalou": ["Gathanji", "Ol Kalou", "Ol Joro Orok", "Karau", "Kanjuiri Ridge"],
        "Ol Jorok": ["Gatimu", "Weru", "Charagita", "Mirangine"],
        "Ndaragwa": ["Leshau", "Pondo", "Shamata", "Ndaragwa"],
    },
    "Nyeri": {
        "Tetu": ["Dedan Kimathi", "Wamagana", "Aguthi-Gaaki"],
        "Kieni": ["Mweiga", "Naromoru/Kiamathaga", "Nanyuki", "Mukurwe-ini West", "Gatarakwa"],
        "Mathira": ["Ruguru", "Karatina Town", "Mahiga", "Iria-ini", "Chinga", "Konyu"],
        "Othaya": ["Gaturi", "South Tetu", "Iria-ini", "Chinga"],
        "Mukurweini": ["Mukurweini West", "Mukurweini East", "Gikondi", "Ruchu"],
        "Nyeri Town": ["Gatitu/Muruguru", "Rware", "King'ong'o", "Nyaribo", "Thegu River"],
    },
    "Kirinyaga": {
        "Mwea": ["Mutithi", "Kangai", "Wamumu", "Nyangati", "Murinduko", "Gathigiriri", "Tebere", "Nyakagoto"],
        "Gichugu": ["Kabare", "Kerugoya", "Inoi", "Ngariama", "Baragwi"],
        "Ndia": ["Kiine", "Karumandi", "Mukure", "Ndia", "Gatitu"],
        "Kirinyaga Central": ["Mutira", "Kanyekini", "Kerugoya", "Ciagini"],
    },
    "Murang'a": {
        "Kangema": ["Kanyenya-ini", "Muguru", "Rwathia"],
        "Mathioya": ["Gitugi", "Kiru", "Kamacharia"],
        "Kiharu": ["Wangu", "Mugoiri", "Mbiri", "Township", "Murarandia", "Gaturi"],
        "Kigumo": ["Kigumo", "Kinyona", "Kariti", "Muthithi", "Ithiru", "Ruchu"],
        "Maragwa": ["Kimorori/Wempa", "Makuyu", "Kambiti", "Kamahuha", "Ichagaki"],
        "Kandara": ["Ng'araria", "Muruka", "Kagundu-ini", "Gaichanjiru", "Ithiru", "Ruchu"],
        "Gatanga": ["Ithanga", "Kakuzi/Mitubiri", "Mugutha", "Muthithi", "Kihumbu"],
    },
    "Kiambu": {
        "Gatundu South": ["Kiganjo/Matathia", "Ndarugu", "Ngenda", "Kanunga", "Githobokoni"],
        "Gatundu North": ["Gachoka/Mang'u", "Igwamiti", "Kakuzi/Mitubiri", "Mugutha"],
        "Juja": ["Theta", "Juja", "Witeithie", "Kalimoni", "Murera"],
        "Thika Town": ["Township", "Kamenu", "Hospital", "Gatuanyaga", "Ngoliba"],
        "Ruiru": ["Gitothua", "Biashara", "Kahawa Sukari", "Kahawa Wendani", "Mwiki", "Mwihoko"],
        "Githunguri": ["Githunguri", "Githiga", "Ikinu", "Ngewa", "Komothai"],
        "Kiambu": ["Kiambaa", "Cianda", "Karuri", "Ndumberi", "Riabai"],
        "Kiambaa": ["Ndenderu", "Kihara", "Gitaru", "Muguga", "Ngewe/Kikuyu Escarpment"],
        "Kabete": ["Gitaru", "Muguga", "Ngewe/Kikuyu Escarpment", "Kinoo"],
        "Kikuyu": ["Kikuyu", "Kinoo", "Karai", "Sigona", "Ondiri", "Nachu", "Ruthigiti"],
        "Limuru": ["Limuru Central", "Ndeiya", "Limuru East", "Bibirioni", "Ngecha Tigoni", "Turitu"],
        "Lari": ["Kijabe", "Lari/Kirenga", "Kinale", "Nyanduma", "Kagwe"],
    },
    "Turkana": {
        "Turkana North": ["Kaeris", "Lake Zone", "Lapur", "Nawoyama"],
        "Turkana West": ["Kalobeyei", "Kakuma", "Lopur", "Letea", "Songot", "Kaaleng/Kaichore", "Lokichoggio", "Nanaam"],
        "Turkana Central": ["Kerio Delta", "Lodwar Township", "Kanamkemer", "Lobei", "Napeikar", "Kangirisae"],
        "Loima": ["Kotome", "Lokiriama/Lorengippi", "Turkwel", "Loima"],
        "Turkana South": ["Lobokat", "Kaputir", "Katilu", "Lokori/Kochodin", "Kerio Delta"],
        "Turkana East": ["Kapedo/Napeitom", "Katilu", "Lokori/Kochodin", "Kerio Delta", "Turkwel"],
    },
    "West Pokot": {
        "Kapenguria": ["Sook", "Masool", "Kapenguria", "Mnagei"],
        "Sigor": ["Wei Wei", "Sekerr", "Tapach", "Weiwei"],
        "Kacheliba": ["Kacheliba", "Kodich", "Kanyarkwat", "Alale"],
        "Pokot South": ["Chepareria", "Batei", "Lelan", "Parua"],
    },
    "Samburu": {
        "Samburu West": ["Suguta Marmar", "Maralal", "Loosuk", "Poro", "El Barta"],
        "Samburu North": ["Waso", "Archers Post", "Merti", "Lodokejek"],
        "Samburu East": ["Wamba North", "Wamba West", "Wamba East"],
    },
    "Trans Nzoia": {
        "Kwanza": ["Kwanza", "Keiyo", "Bidii", "Kapomboi"],
        "Endebess": ["Endebess", "Metkei", "Mt. Elgon Forest", "Matumbei"],
        "Saboti": ["Kinyoro", "Matisi", "Tuwani", "Saboti", "Machewa"],
        "Kiminini": ["Kiminini", "Waitaluk", "Sikhendu", "North Matui", "Nabiswa"],
        "Cherangany": ["Sinyerere", "Kaplamai", "Motosiet", "Cherangany/Suwerwa", "Cheptais", "Barwessa"],
    },
    "Uasin Gishu": {
        "Soy": ["Soy", "Moi's Bridge", "Sergoit", "Ziwa", "Huruma"],
        "Turbo": ["Turbo", "Ngenyilel", "Tapsagoi", "Kamagut", "Kiplombe"],
        "Moiben": ["Moiben", "Kuinet/Kapsuswa", "Ainabkoi", "Marura", "Tembelio"],
        "Ainabkoi": ["Ainabkoi/Olare", "Kapsoya", "Kaptagat"],
        "Kapseret": ["Simat/Kapseret", "Megun", "Langas", "Racecourse"],
        "Kesses": ["Tarakwa", "Megun", "Ngenyilel", "Tulwet/Chuiyat"],
    },
    "Elgeyo-Marakwet": {
        "Marakwet East": ["Lelan", "Sengwer", "Endo", "Sambirir"],
        "Marakwet West": ["Embobut/Embulot", "Kapyego", "Soy North", "Chebiemit"],
        "Keiyo North": ["Emsoo", "Kabiemit", "Rokocho", "Tambach"],
        "Keiyo South": ["Chepkorio", "Soy South", "Kaptarakwa", "Kamariny"],
    },
    "Nandi": {
        "Tinderet": ["Tinderet", "Chemase", "Kinaren", "Songhor/Soba"],
        "Aldai": ["Kabwareng", "Terik", "Kemeloi-Maraba", "Kobujoi", "Kaptumo-Kaboi"],
        "Nandi Hills": ["Nandi Hills", "Chepkunyuk", "Ol'lessos", "Kabiyet"],
        "Chesumei": ["Chemundu/Kapng'etuny", "Kosirai", "Lelmokwo/Ngechek", "Kabiyet", "Ndalat"],
        "Emgwen": ["Kapsabet", "Kabisaga", "Chepterit", "Kosirai"],
        "Mosop": ["Kabisaga", "Chepterwai", "Kipchoriat", "Mutwot", "Songhor"],
    },
    "Baringo": {
        "Tiaty": ["Tirioko", "Kolowa", "Ribkwo", "Silale", "Loiyamorock"],
        "Baringo North": ["Baringo Central", "Mochongoi", "Mukutani", "Rarpet"],
        "Baringo Central": ["Kabartonjo", "Saimo/Soi", "Saimo/Kipsaraman", "Ewalel/Chapchap", "Maji Mazuri"],
        "Baringo South": ["Marigat", "Ilchamus", "Mochongoi", "Mukutani"],
        "Mogotio": ["Mogotio", "Emining", "Kisanana"],
        "Eldama Ravine": ["Eldama Ravine", "Lembus", "Lembus Kwen", "Ravine", "Rongai"],
    },
    "Laikipia": {
        "Laikipia West": ["Ol-Moran", "Rumuruti Township", "Githiga", "Marmanet", "Igwamiti"],
        "Laikipia East": ["Ngobit", "Tigithi", "Thingithu", "Nanyuki", "Majusi"],
        "Laikipia North": ["Mukogodo West", "Mukogodo East", "Ol Moran", "Olmoran"],
    },
    "Nakuru": {
        "Molo": ["Mariashoni", "Elburgon", "Molo", "Turi"],
        "Njoro": ["Mau Narok", "Mauche", "Kihingo", "Nessuit", "Lare", "Njoro"],
        "Naivasha": ["Naivasha East", "South Lake", "Biashara", "Hells Gate", "Lake View", "Mai Mahiu", "Olkaria", "Naivasha", "Viwandani"],
        "Gilgil": ["Gilgil", "Mbaruk/Eburu", "Malewa West", "Kiambogo"],
        "Kuresoi South": ["Amalo", "Keringet", "Kiptagich", "Tinet"],
        "Kuresoi North": ["Kiptororo", "Nyota", "Sirikwa", "Kamara"],
        "Subukia": ["Subukia", "Waseges", "Kabazi"],
        "Rongai": ["Menengai West", "Soin", "Visoi", "Mosop", "Solai"],
        "Bahati": ["Bahati", "Lanet/Umoja", "Dundori", "London"],
        "Nakuru Town West": ["Barut", "London", "Kaptembwo", "Kapkures", "Rhonda"],
        "Nakuru Town East": ["Biashara", "Kivumbini", "Flamingo", "Menengai", "Hospital"],
    },
    "Narok": {
        "Kilgoris": ["Shankoe", "Keyian", "Angata Barikoi", "Siana", "Lemek"],
        "Emurua Dikirr": ["Emurua Dikirr", "Kimintet", "Ilkisonko", "Mosiro"],
        "Narok North": ["Melelo", "Mara", "Ololmasani", "Muggers", "Sogoo"],
        "Narok East": ["Ildamat", "Keekonyokie", "Dalalekutuk", "Matapato North", "Matapato South"],
        "Narok South": ["Majimoto/Naroosura", "Ololulung'a", "Melelo", "Loita", "Mosiro"],
        "Narok West": ["Ilkisonko", "Keekonyokie", "Mosiro", "Narok North"],
    },
    "Kajiado": {
        "Kajiado North": ["Olkeri", "Ongata Rongai", "Nkaimurunya", "Oloolua", "Ngong"],
        "Kajiado Central": ["Purko", "Ildamat", "Dalalekutuk", "Matapato North", "Matapato South"],
        "Kajiado East": ["Kajiado East", "Oloitokitok", "Rombo", "Entomoniot", "Imaroro"],
        "Kajiado West": ["Magadi", "Ewuaso Oonkidong'i", "Mosiro", "Kajiado West"],
        "Kajiado South": ["Kajiado South", "Oloitokitok", "Rombo", "Imaroro"],
    },
    "Kericho": {
        "Kipkelion East": ["Londiani", "Kedowa/Kimugul", "Chepseon", "Tendeno/Sorget"],
        "Kipkelion West": ["Kipkelion", "Kunyak", "Kamasian"],
        "Ainamoi": ["Ainamoi", "Kapkugerwet", "Kapsoit"],
        "Bureti": ["Litein", "Cheplanget", "Kapkatet", "Fort Ternan"],
        "Belgut": ["Waldai", "Kabianga", "Cheptabutany", "Kisiara"],
        "Sigowet/Soin": ["Sigowet", "Soin", "Kaplelartet", "Silibwet Township"],
    },
    "Bomet": {
        "Sotik": ["Sotik", "Ndanai/Abosi", "Chemagel", "Kipreres", "Longisa"],
        "Chepalungu": ["Sigor", "Siongiroi", "Merigi", "Kongasis", "Nyongores"],
        "Bomet East": ["Kembu", "Township", "Silibwet Township", "Ndaraweta"],
        "Bomet Central": ["Mutarakwa", "Singorwet", "Chesoen", "Rongena/Manaret"],
        "Konoin": ["Kimulot", "Mogogosiek", "Cheborge", "Embomos"],
    },
    "Kakamega": {
        "Lugari": ["Lugari", "Lumakanda", "Chekalini", "Chevaywa", "Segero/Bungoma East"],
        "Likuyani": ["Sango", "Nzoia", "Mautuma", "Nzoia East"],
        "Malava": ["Central Malava", "Butali/Chegulo", "Manda-Shivanga", "Shirugu-Mugai", "South Kabras"],
        "Lurambi": ["Mahiakalo", "East Kabras", "Shirere", "Rosterman", "Sheywe"],
        "Navakholo": ["Ingotse-Matungu", "Ikolomani", "Navakholo", "West Kabras"],
        "Mumias West": ["Mumias Central", "Etenje", "Mumias North"],
        "Mumias East": ["Lusheya/Lubinu", "Malaha/Isongo/Makunga", "East Wanga"],
        "Matungu": ["Koyonzo", "Kholera", "Mayoni", "Namamali"],
        "Butere": ["Marama North", "Marama West", "Marama Central", "Marama South", "Marango"],
        "Khwisero": ["Kisa North", "Kisa East", "Kisa West", "Kisa Central"],
        "Shinyalu": ["North East Kabras", "Shinoyi/Shikomari/Esumeyia", "Isukha North", "Isukha Central", "Isukha West"],
        "Ikolomani": ["Idakho East", "Idakho West", "Idakho South", "Idakho North", "Shirere"],
    },
    "Vihiga": {
        "Vihiga": ["Luanda South", "Vihiga", "Lugaga-Wamuluma", "South Maragoli", "Central Maragoli"],
        "Sabatia": ["Ikonzo/Itende", "Mwibona", "Sabatia", "Shaviringa", "Tambua"],
        "Hamisi": ["Shiru", "Gisambai", "Shamakhokho", "Banja", "Muhudu", "Jepkoyai"],
        "Luanda": ["Luanda Township", "Emabungo", "North East Bunyore", "West Bunyore", "East Bunyore"],
        "Emuhaya": ["North East Bunyore", "West Bunyore", "East Bunyore", "Emuhaya North", "Emuhaya Central"],
    },
    "Bungoma": {
        "Mt. Elgon": ["Cheptais", "Chesikaki", "Chepyuk", "Kapkateny", "Kaptama", "Elgon"],
        "Sirisia": ["Malakisi/South Kulisiru", "Lwandanyi", "Sirisia", "Namwela"],
        "Kabuchai": ["Kabuchai/Chwele", "West Nalondo", "Bwake/Luuya", "Mukuyuni"],
        "Bumula": ["North Bukusu", "Bumula", "Khasoko", "Kabula", "Kimaeti", "West Bukusu/Sirisia"],
        "Kanduyi": ["Musikoma", "East Sangalo", "West Sangalo", "Central Sangalo", "Township", "Marakaru/Tuuti"],
        "Webuye East": ["Maraka", "Ndivisi", "Mihuu", "Matulo"],
        "Webuye West": ["Sitikho", "Tande", "Luandeti", "Bukhayo North/Mishikambi"],
        "Kimilili": ["Kimilili", "Maeni", "Kamukuywa", "Kibingei"],
        "Tongaren": ["Tongaren", "Naitiri/Kabuyefwe", "Milima", "Ndalu/Tabani", "Kuywa"],
    },
    "Busia": {
        "Teso North": ["Malaba Central", "Malaba North", "Ang'urai South", "Ang'urai North", "Ang'urai East", "Malaba South"],
        "Teso South": ["Amukura East", "Amukura West", "Amukura Central", "Chakol South", "Chakol North"],
        "Nambale": ["Nambale Township", "Bukhayo East/Walatsi"],
        "Matayos": ["South Funyula", "Butula", "Kingandole", "Marachi East", "Marachi Central", "Marachi West", "Marachi North"],
        "Butula": ["Elugulu", "Sikinga", "Nangina", "Ageng'a Nanguba"],
        "Funyula": ["Funyula", "Mukhweya/Lupida", "Matayos South"],
        "Budalangi": ["Budalangi Central", "Budumba", "Ruambwa", "Namboboto Nambuku"],
    },
    "Siaya": {
        "Ugenya": ["East Ugenya", "Ukwala", "North Ugenya", "West Ugenya"],
        "Ugunja": ["Ugunja", "Sigomere", "South Ugenya"],
        "Alego Usonga": ["Central Alego", "Siaya Township", "North Alego", "South East Alego", "Usonga", "West Alego"],
        "Gem": ["North Gem", "East Gem", "West Gem", "Central Gem", "South Gem", "Yala Township"],
        "Bondo": ["Bondo Township", "Maranda", "Got Kachola", "Usigu", "Nyang'oma", "Nyabondo"],
        "Rarieda": ["East Asembo", "West Asembo", "North Uyoma", "South Uyoma", "Uyoma"],
    },
    "Kisumu": {
        "Kisumu East": ["Kajulu", "Kolwa East", "Manyatta B", "Nyalenda A", "Kolwa Central"],
        "Kisumu West": ["South West Kisumu", "Central Kisumu", "Kisumu North", "West Kisumu", "North West Kisumu"],
        "Kisumu Central": ["Railways", "Migosi", "Shaurimoyo Kaloleni", "Market Milimani", "Kondele", "Nyalenda B"],
        "Seme": ["West Seme", "Central Seme", "East Seme", "North Seme"],
        "Nyando": ["East Kano/Wawidhi", "Awasi/Onjiko", "Ahero", "Kabonyo/Kanyagwal", "Kobura"],
        "Muhoroni": ["Miwani", "Ombeyi", "Masogo/Nyang'oma", "Chemelil/Songhor", "Muhoroni/Koru"],
        "Nyakach": ["North East Nyakach", "South West Nyakach", "Central Nyakach", "West Nyakach", "South Nyakach"],
    },
    "Homa Bay": {
        "Kasipul": ["West Kasipul", "Central Kasipul", "South Kasipul", "Rowo", "East Kamagak", "West Kamagak"],
        "Kabondo Kasipul": ["Kabondo East", "Kokwanyo/Kakelo", "Kojwach", "Kabondo West"],
        "Karachuonyo": ["North Karachuonyo", "West Karachuonyo", "Central Karachuonyo", "Kendu Bay Town", "East Karachuonyo", "Oyugis"],
        "Rangwe": ["East Kochia", "Kagan", "Kochia Central", "West Kochia"],
        "Homa Bay Town": ["Homa Bay Central", "Homa Bay Arujo", "Homa Bay West", "Homa Bay East"],
        "Ndhiwa": ["Kwabwai", "Kanyadoto", "Kanyikela", "Kabuoch North", "Kabuoch South/Kabonyo", "Kanyamwa Kosewe", "Kanyamwa Kologi"],
        "Mbita": ["Mfangano Island", "Rusinga Island", "Kaksingri West", "Gwassi South", "Gwassi North", "Lambwe"],
        "Suba North": ["Gwassi South", "Gwassi North", "Lambwe", "Gembe"],
        "Suba South": ["Ruma Kaksingri", "West Kadem", "Kanyadoto"],
    },
    "Migori": {
        "Rongo": ["North Kadem", "Wasimbete", "West Kadem", "Migori Township"],
        "Awendo": ["North Sakwa", "South Sakwa", "Central Sakwa", "East Sakwa"],
        "Suna East": ["Wiga", "Kakrao", "God Jope", "Suna Central", "Kwa"],
        "Suna West": ["Ragana-Oruba", "Wasimbete", "Wasweta II", "Kachien'g"],
        "Nyatike": ["Kachieng", "Kanyasa", "North Kabuoch", "West Kanyamkago", "Central Kanyamkago", "East Kanyamkago"],
        "Uriri": ["Uriri", "West Kanyamkago", "North Kanyamkago", "Central Kanyamkago"],
        "Kuria West": ["Masaba North", "Bukira East", "Bukira Central/Ikerege", "Isibania", "Makerero", "Tagare"],
        "Kuria East": ["Kehancha", "Kuria East", "Ntimaru West", "Ntimaru East", "Nyabasi East", "Nyabasi West"],
    },
    "Kisii": {
        "Bonchari": ["Bogiakumu", "Riana", "Masige West", "Masige East", "Bomorenda"],
        "South Mugirango": ["Bogeka", "Nyacheki", "Boochi/Tendere", "Boochi West", "Gesieka"],
        "Bomachoge Borabu": ["Borabu", "Moticho", "Gachuba", "Bomachoge", "Boochi East"],
        "Bobasi": ["Bosoti/Sengera", "Moticho", "Gachuba", "Bobasi South", "Masige"],
        "Bomachoge Chache": ["Ichuni", "Nyanturago", "Oromeindo", "Majoge Bossi", "Masige"],
        "Nyaribari Masaba": ["Iranda", "Nyakoe", "Kiamokama", "Boochi/Tendere", "Booke/Moticho"],
        "Nyaribari Chache": ["Township", "Griget", "Soba", "Bogiakumu", "Riana"],
        "Kitutu Chache North": ["Mwembe", "Rigoma", "Gachuba", "Marani", "Kiogo"],
        "Kitutu Chache South": ["Boombori", "Ekerenyo", "Nyansiongo", "Kiango"],
    },
    "Nyamira": {
        "Kitutu Masaba": ["Rigoma", "Gachuba", "Boochi/Tendere", "Magwagwa", "Ekerenyo"],
        "West Mugirango": ["Nduru", "Nyamira North", "Bojii", "Magombo", "Bomwagamo"],
        "North Mugirango": ["Itibo", "Bomwagamo", "Bonyamatuta", "Township", "Nyansiongo"],
        "Borabu": ["Metembe", "Borabu", "Moticho", "Gachuba", "Manga"],
    },
    "Nairobi": {
        "Westlands": ["Kitisuru", "Parklands/Highridge", "Karura", "Kangemi", "Mountain View"],
        "Dagoretti North": ["Kilimani", "Kawangware", "Gatina", "Kileleshwa", "Kabiro"],
        "Dagoretti South": ["Mutu-ini", "Ngando", "Riruta", "Uthiru/Ruthimitu", "Waithaka"],
        "Langata": ["Karen", "Nairobi West", "Mugumu-ini", "South C", "Nyayo Highrise"],
        "Kibra": ["Laini Saba", "Lindi", "Makina", "Woodley/Kenyatta Golf Course", "Sarang'ombe"],
        "Roysambu": ["Githurai", "Kahawa West", "Zimmerman", "Roysambu", "Clay City"],
        "Kasarani": ["Clayworks", "Mwiki", "Kasarani", "Njiru", "Ruai"],
        "Ruaraka": ["Baba Dogo", "Utalii", "Mathare North", "Lucky Summer", "Korogocho"],
        "Embakasi South": ["Imara Daima", "Kwa Njenga", "Kwa Reuben", "Pipeline", "Mwangi"],
        "Embakasi North": ["Kariobangi North", "Dandora Area I", "Dandora Area II", "Dandora Area III", "Dandora Area IV"],
        "Embakasi Central": ["Kayole North", "Kayole Central", "Kayole South", "Komarock", "Matopeni/Spring Valley"],
        "Embakasi East": ["Upper Savanna", "Lower Savanna", "Embakasi", "Utawala", "Mihango"],
        "Embakasi West": ["Umoja I", "Umoja II", "Mowlem", "Kariobangi South"],
        "Makadara": ["Maringo/Hamza", "Viwandani", "Harambee", "Makongeni"],
        "Kamukunji": ["Pumwani", "Eastleigh North", "Eastleigh South", "Airbase", "California"],
        "Starehe": ["Township", "Pangani", "Ziwani/Kariokor", "Landimawe", "Nairobi Central"],
        "Mathare": ["Hospital", "Mabatini", "Huruma", "Ngei", "Mlango Kubwa", "Kiamaiko"],
    },
}
